### ISSUE TITLE
Refining pull requests regarding Django-4 compatibility

### ISSUE THREAD

**Issue by raratiru** [gadventures/django-fsm-admin#102]
... #101 #100 and #99 provide Django-4 support. 

Which one is the winner?

**Comment by lnagel** [comment]
@raratiru Perhaps you could edit your issue title and description to be less aggressive in wording? This is after all a free software project that takes volunteer efforts to run.

The obvious question here is that are there any blockers that prevent releasing a Django 4 compatible version?

I can offer help to resolve any remaining issues if needed.

**Comment by raratiru** [comment]
Indeed, I apologize and I have changed the title. 

I was about to start a pull request for this issue but there are already 3. 

* #101 seems to not cater of older versions but it certainly works on Django-4.0
* #100 fixes the same issues as #101 in a way that compatibility would be preserved
* #99 applies the same fixes as #100 along with changes in `requirements.txt`, `urls.py` in the example, refines `setup.py` and also bumps the version in `__init__.py`

I would vote for #99 .

**Comment by blueyed** [comment]
There is also https://github.com/gadventures/django-fsm-admin/pull/92.

**Comment by blueyed** [comment]
@marz619 are you planning to address pending PRs?

**Comment by raratiru** [comment]
@blueyed  Yes! The winner is #92 !
