### ISSUE TITLE
add django.core.context_processors.request to example project 

### ISSUE THREAD

**Issue by seddonym** [gadventures/django-fsm-admin#30]
This should be added to the example project's `settings.py`, otherwise it doesn't work:
    
    from django.conf import global_settings

    TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + (
        'django.core.context_processors.request',
    )

**Comment by Nagyman** [comment]
Thanks resolved by PR#27
