### ISSUE TITLE
Inline save order

### ISSUE THREAD

**Issue by nwaxiomatic** [gadventures/django-fsm-admin#37]
In the FSM Mixin for save_model, the transition is executed before the saving of the model, which causes the inlines to be saved after the transition has occurred.

Is this on purpose? Is there any reason this order was chosen?

If there are post signals attached to the transition which involve the related models, they won't take into account the modifications through the inlines in the current setup.

**Comment by nwaxiomatic** [comment]
Actually is this is just related to the save order of parent and inlines in general
http://stackoverflow.com/questions/14858559/save-the-related-objects-before-the-actual-object-being-edited-on-django-admin

will implement custom solution and probably post here afterwards in case anyone in the future looks

**Comment by HJEGeorge** [comment]
> will implement custom solution and probably post here afterwards in case anyone in the future looks

Did you end up creating a solution? I am also having this problem
