### ISSUE TITLE
State translation in the admin

### ISSUE THREAD

**Issue by khlumzeemee** [gadventures/django-fsm-admin#38]
Hi,

I defined the states as a choice list to be able to translate the labels.
However this does not reflect in the admin panel, the state is still displayed as "new" (the key) where I was expecting "New" (the value)

Am I missing something?

```
    #States are listed as choices to be translatable
    NEW = 'new'
    ACCEPTED = 'accepted'
    AWAITING_REVIEW = 'awaiting_review'
    REVIEWED = 'reviewed'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'
    REJECTED = 'rejected'
    
    STATES = (
        (NEW, _('New')),
        (ACCEPTED, _('Accepted')),
        (AWAITING_REVIEW, _('Awaiting Review')),
        (REVIEWED, _('Reviewed')),
        (COMPLETED, _('Completed')),
        (CANCELLED, _('Cancelled')),
        (REJECTED, _('Rejected')),
    )
    
    state = FSMField(_('state'), default=NEW, protected=True)
```

**Comment by Nagyman** [comment]
The button's name defaults to the function name which can be overridden by custom configuration of the transition (logic is here: https://github.com/gadventures/django-fsm-admin/blob/44df125462be833f9d4d48dd363b058ccb40b298/fsm_admin/templatetags/fsm_admin.py#L48)

For example:

    @transition(
        field=revision_state,
        source=RevisionState.DRAFT,
        target=RevisionState.COPY,
        conditions=draft_to_copy_conditions,
        permission='dossiers.revise_dossier',
        custom={'button_name': _('Ready for Copy')})
    def ready_for_copy(self):
        pass

**Comment by khlumzeemee** [comment]
Hi,
so you are telling me that my choice list is useless :)

How about the state itself (displayed as a non editable FSMfield in my case)? The value displayed in the form is the key, not the value.

**Comment by Nagyman** [comment]
@khlumzeemee the FSMField is managed as part of the [django-fsm](https://github.com/kmmbvnr/django-fsm) project itself, so you'd have to bring that issue to them. This project is a small utility using django-fsm :)

**Comment by khlumzeemee** [comment]
Hi,
FYI the issue is solved in case you were wondering. using the ```choices``` attributes, the label is now displayed correctly in the admin.

**Comment by Nagyman** [comment]
Happy you found a solution @khlumzeemee !
