### ISSUE TITLE
Transition condition can't access User obejct

### ISSUE THREAD

**Issue by jrief** [gadventures/django-fsm-admin#53]
In order to allow certain transitions only to a set of staff users, I'd like to access the User object inside my customized condition functions.

This unfortunately is not possible, because that function never "sees" the ``request`` object. By patching the templatetag function ``fsm_transition_hints`` and the method ``FSMTransitionMixin.get_transition_hints()`` is would easily by possible to pass to ``request`` object to my condition function.

If you have concerns about backward compatibility with existing condition functions, I could add a boolean named, say ``pass_request`` to the ``custom`` dict. Then the ``request`` object is passed in only when this is ``True``. 

What do you think about this and shall I create a pull request for this feature?

**Comment by Nagyman** [comment]
`_fsm_get_transitions` passes along the user object to `get_available_user_{state_field}_transitions` which allows for restricting which buttons appear. See: https://github.com/gadventures/django-fsm-admin/blob/3245f68ccaf38f1def16da69ce6a13919f75860d/fsm_admin/mixins.py#L50

`fsm_transition_hints` takes context, which _should_ contain the request and therefore the user.

As for passing that request/user along to the conditions for checking... the decorator supports "permissions" https://github.com/kmmbvnr/django-fsm#permissions.

Let me know if you still think things need adjustment. I'm happy to review a PR.

**Comment by jrief** [comment]
Thanks @Nagyman 
Haven't look at django-fsm permissions. Thanks for the hint. Will try out soon.

**Comment by jrief** [comment]
FSM ``@transition(... permission=lambda instance, user: ...)`` works as expected. Many thanks.
