### ISSUE TITLE
Django 1.10: AttributeError: 'Options' object has no attribute 'get_field_by_name'

### ISSUE THREAD

**Issue by dmitry-nazarov** [gadventures/django-fsm-admin#63]
mixins.py: `fsmfield = obj._meta.get_field_by_name(field)[0]`

It's about bringing django 1.10 support to the table, right?..

**Comment by florianm** [comment]
I've got the same problem - a very quick and dirty hack:

mixins l78: 
- return self.model._meta.get_field_by_name(fsm_field_name)[0]
+ return self.model._meta.get_field(fsm_field_name)

same in mixins.py l225:  fsmfield = obj._meta.get_field(field)
